#!/bin/bash

CONDAENVNAME=itermship

BASEDIR=$HOME/git/python/${CONDAENVNAME}
[ -n "$(type -t brew)" ] && \
    PATH=$( brew --caskroom)/miniconda/base/envs/${CONDAENVNAME}/bin:$PATH

exec $BASEDIR/itermship.py
